## Preparacion de los Datos

### 1) Cargar el dataset

In [1]:
import pandas as pd

# Cargar el archivo
df = pd.read_csv("telecomx_clean.csv")

# Verificar estructura
df.head()

,ClienteID,Churn,Genero,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Lineas_Multiples,Servicio_Internet,...,Soporte_Tecnico,Streaming_TV,Streaming_Peliculas,Tipo_Contrato,Factura_Electronica,Metodo_Pago,Cargo_Mensual,Cargo_Total,Cuentas_Diarias,Cantidad_Servicios
0,0002-ORFBO,0,Female,0,1,1,9,1,No,DSL,...,Yes,Yes,No,One year,1,Mailed check,65.6,593.30,2.186667,3
1,0003-MKNFE,0,Male,0,0,0,9,1,Yes,DSL,...,No,No,Yes,Month-to-month,0,Mailed check,59.9,542.40,1.996667,1
2,0004-TLHLJ,1,Male,0,0,0,4,1,No,Fiber optic,...,No,No,No,Month-to-month,1,Electronic check,73.9,280.85,2.463333,1
3,0011-IGKFF,1,Male,1,1,0,13,1,No,Fiber optic,...,No,Yes,Yes,Month-to-month,1,Electronic check,98.0,1237.85,3.266667,4
4,0013-EXCHZ,1,Female,1,1,0,3,1,No,Fiber optic,...,Yes,Yes,No,Month-to-month,1,Mailed check,83.9,267.40,2.796667,2

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 23 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   ClienteID               7043 non-null   object
 1   Churn                   7043 non-null   int64
 2   Genero                  7043 non-null   object
 3   Adulto_Mayor            7043 non-null   int64
 4   Tiene_Pareja            7043 non-null   int64
 5   Tiene_Dependientes      7043 non-null   int64
 6   Antiguedad_Meses        7043 non-null   int64
 7   Servicio_Telefono       7043 non-null   int64
 8   Lineas_Multiples        7043 non-null   object
 9   Servicio_Internet       7043 non-null   object
 10  Seguridad_Online        7043 non-null   object
 11  Backup_Online           7043 non-null   object
 12  Proteccion_Dispositivo  7043 non-null   object
 13  Soporte_Tecnico         7043 non-null   object
 14  Streaming_TV            7043 non-null   object
 15  Streaming_Peliculas     7043 non-null   object
 16  Tipo_Contrato           7043 non-null   object
 17  Factura_Electronica     7043 non-null   int64
 18  Metodo_Pago             7043 non-null   object
 19  Cargo_Mensual           7043 non-null   float64
 20  Cargo_Total             7043 non-null   float64
 21  Cuentas_Diarias         7043 non-null   float64
 22  Cantidad_Servicios      7043 non-null   int64
dtypes: float64(3), int64(8), object(12)
memory usage: 1.2+ MB

In [3]:
df.describe()

,Churn,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Factura_Electronica,Cargo_Mensual,Cargo_Total,Cuentas_Diarias,Cantidad_Servicios
count,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000,7043.000000
mean,0.265370,0.162147,0.483033,0.299588,32.371149,0.903166,0.592219,64.761692,2279.734304,2.158723,2.037910
std,0.441561,0.368612,0.499748,0.458110,24.559481,0.295752,0.491457,30.090047,2266.794470,1.003002,1.847682
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,18.250000,0.000000,0.608333,0.000000
25%,0.000000,0.000000,0.000000,0.000000,9.000000,1.000000,0.000000,35.500000,398.550000,1.183333,0.000000
50%,0.000000,0.000000,0.000000,0.000000,29.000000,1.000000,1.000000,70.350000,1394.550000,2.345000,2.000000
75%,1.000000,0.000000,1.000000,1.000000,55.000000,1.000000,1.000000,89.850000,3786.600000,2.995000,3.000000
max,1.000000,1.000000,1.000000,1.000000,72.000000,1.000000,1.000000,118.750000,8684.800000,3.958333,6.000000

In [4]:
df["Churn"].value_counts()

Churn
0    5174
1    1869
Name: count, dtype: int64

### 2) Eliminación de Columnas Irrelevantes

In [5]:
df = df.drop(columns=["ClienteID"])

# Verificamos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Churn                   7043 non-null   int64
 1   Genero                  7043 non-null   object
 2   Adulto_Mayor            7043 non-null   int64
 3   Tiene_Pareja            7043 non-null   int64
 4   Tiene_Dependientes      7043 non-null   int64
 5   Antiguedad_Meses        7043 non-null   int64
 6   Servicio_Telefono       7043 non-null   int64
 7   Lineas_Multiples        7043 non-null   object
 8   Servicio_Internet       7043 non-null   object
 9   Seguridad_Online        7043 non-null   object
 10  Backup_Online           7043 non-null   object
 11  Proteccion_Dispositivo  7043 non-null   object
 12  Soporte_Tecnico         7043 non-null   object
 13  Streaming_TV            7043 non-null   object
 14  Streaming_Peliculas     7043 non-null   object
 15  Tipo_Contrato           7043 non-null   object
 16  Factura_Electronica     7043 non-null   int64
 17  Metodo_Pago             7043 non-null   object
 18  Cargo_Mensual           7043 non-null   float64
 19  Cargo_Total             7043 non-null   float64
 20  Cuentas_Diarias         7043 non-null   float64
 21  Cantidad_Servicios      7043 non-null   int64
dtypes: float64(3), int64(8), object(11)
memory usage: 1.2+ MB

### 3) Embeddings

#### 3.1) Analisis de variables

In [6]:
df.select_dtypes(include="object").columns

Index(['Genero', 'Lineas_Multiples', 'Servicio_Internet', 'Seguridad_Online',
       'Backup_Online', 'Proteccion_Dispositivo', 'Soporte_Tecnico',
       'Streaming_TV', 'Streaming_Peliculas', 'Tipo_Contrato', 'Metodo_Pago'],
      dtype='object')

In [7]:
for col in df.select_dtypes(include="object").columns:
    print(col)
    print(df[col].unique())
    print("-----")

Genero
['Female' 'Male']
-----
Lineas_Multiples
['No' 'Yes' 'No phone service']
-----
Servicio_Internet
['DSL' 'Fiber optic' 'No']
-----
Seguridad_Online
['No' 'Yes' 'No internet service']
-----
Backup_Online
['Yes' 'No' 'No internet service']
-----
Proteccion_Dispositivo
['No' 'Yes' 'No internet service']
-----
Soporte_Tecnico
['Yes' 'No' 'No internet service']
-----
Streaming_TV
['Yes' 'No' 'No internet service']
-----
Streaming_Peliculas
['No' 'Yes' 'No internet service']
-----
Tipo_Contrato
['One year' 'Month-to-month' 'Two year']
-----
Metodo_Pago
['Mailed check' 'Electronic check' 'Credit card (automatic)'
 'Bank transfer (automatic)']
-----

#### 3.2) Clasificación de tus variables categóricas

In [8]:
# Convertir "Genero" a numérico

df["Genero"] = df["Genero"].map({"Female": 0, "Male": 1}) # Convertir a numérico

df["Genero"].value_counts()

Genero
1    3555
0    3488
Name: count, dtype: int64

In [9]:
# Convertir "Lineas_Multiples" a numérico

df["Lineas_Multiples"] = df["Lineas_Multiples"].replace("No phone service", "No")
df["Lineas_Multiples"] = df["Lineas_Multiples"].map({"No": 0, "Yes": 1})

df["Lineas_Multiples"].value_counts()

Lineas_Multiples
0    4072
1    2971
Name: count, dtype: int64

In [10]:
# Convertir servicios de internet a numérico

cols_internet = [
    "Seguridad_Online",
    "Backup_Online",
    "Proteccion_Dispositivo",
    "Soporte_Tecnico",
    "Streaming_TV",
    "Streaming_Peliculas"
]

for col in cols_internet:
    df[col] = df[col].replace("No internet service", "No")
    df[col] = df[col].map({"No": 0, "Yes": 1})

In [ ]:
df = pd.get_dummies(
    df,
    columns=["Servicio_Internet", "Tipo_Contrato", "Metodo_Pago"],
    drop_first=True
) # Convertir variables categóricas a dummies

In [ ]:
df.info() # Verificar que todo esté en formato numérico

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Churn                                7043 non-null   int64
 1   Genero                               7043 non-null   int64
 2   Adulto_Mayor                         7043 non-null   int64
 3   Tiene_Pareja                         7043 non-null   int64
 4   Tiene_Dependientes                   7043 non-null   int64
 5   Antiguedad_Meses                     7043 non-null   int64
 6   Servicio_Telefono                    7043 non-null   int64
 7   Lineas_Multiples                     7043 non-null   int64
 8   Seguridad_Online                     7043 non-null   int64
 9   Backup_Online                        7043 non-null   int64
 10  Proteccion_Dispositivo               7043 non-null   int64
 11  Soporte_Tecnico                      7043 non-null   int64
 12  Streaming_TV                         7043 non-null   int64
 13  Streaming_Peliculas                  7043 non-null   int64
 14  Factura_Electronica                  7043 non-null   int64
 15  Cargo_Mensual                        7043 non-null   float64
 16  Cargo_Total                          7043 non-null   float64
 17  Cuentas_Diarias                      7043 non-null   float64
 18  Cantidad_Servicios                   7043 non-null   int64
 19  Servicio_Internet_Fiber optic        7043 non-null   bool
 20  Servicio_Internet_No                 7043 non-null   bool
 21  Tipo_Contrato_One year               7043 non-null   bool
 22  Tipo_Contrato_Two year               7043 non-null   bool
 23  Metodo_Pago_Credit card (automatic)  7043 non-null   bool
 24  Metodo_Pago_Electronic check         7043 non-null   bool
 25  Metodo_Pago_Mailed check             7043 non-null   bool
dtypes: bool(7), float64(3), int64(16)
memory usage: 1.1 MB

In [ ]:
df.head() # Verificar la transformación final

,Churn,Genero,Adulto_Mayor,Tiene_Pareja,Tiene_Dependientes,Antiguedad_Meses,Servicio_Telefono,Lineas_Multiples,Seguridad_Online,Backup_Online,...,Cargo_Total,Cuentas_Diarias,Cantidad_Servicios,Servicio_Internet_Fiber optic,Servicio_Internet_No,Tipo_Contrato_One year,Tipo_Contrato_Two year,Metodo_Pago_Credit card (automatic),Metodo_Pago_Electronic check,Metodo_Pago_Mailed check
0,0,0,0,1,1,9,1,0,0,1,...,593.30,2.186667,3,False,False,True,False,False,False,True
1,0,1,0,0,0,9,1,1,0,0,...,542.40,1.996667,1,False,False,False,False,False,False,True
2,1,1,0,0,0,4,1,0,0,0,...,280.85,2.463333,1,True,False,False,False,False,True,False
3,1,1,1,1,0,13,1,0,0,1,...,1237.85,3.266667,4,True,False,False,False,False,True,False
4,1,0,1,1,0,3,1,0,0,0,...,267.40,2.796667,2,True,False,False,False,False,False,True

In [14]:
# Convertir columnas booleanas a numéricas

bool_cols = df.select_dtypes(include="bool").columns
df[bool_cols] = df[bool_cols].astype(int)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 26 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   Churn                                7043 non-null   int64
 1   Genero                               7043 non-null   int64
 2   Adulto_Mayor                         7043 non-null   int64
 3   Tiene_Pareja                         7043 non-null   int64
 4   Tiene_Dependientes                   7043 non-null   int64
 5   Antiguedad_Meses                     7043 non-null   int64
 6   Servicio_Telefono                    7043 non-null   int64
 7   Lineas_Multiples                     7043 non-null   int64
 8   Seguridad_Online                     7043 non-null   int64
 9   Backup_Online                        7043 non-null   int64
 10  Proteccion_Dispositivo               7043 non-null   int64
 11  Soporte_Tecnico                      7043 non-null   int64
 12  Streaming_TV                         7043 non-null   int64
 13  Streaming_Peliculas                  7043 non-null   int64
 14  Factura_Electronica                  7043 non-null   int64
 15  Cargo_Mensual                        7043 non-null   float64
 16  Cargo_Total                          7043 non-null   float64
 17  Cuentas_Diarias                      7043 non-null   float64
 18  Cantidad_Servicios                   7043 non-null   int64
 19  Servicio_Internet_Fiber optic        7043 non-null   int64
 20  Servicio_Internet_No                 7043 non-null   int64
 21  Tipo_Contrato_One year               7043 non-null   int64
 22  Tipo_Contrato_Two year               7043 non-null   int64
 23  Metodo_Pago_Credit card (automatic)  7043 non-null   int64
 24  Metodo_Pago_Electronic check         7043 non-null   int64
 25  Metodo_Pago_Mailed check             7043 non-null   int64
dtypes: float64(3), int64(23)
memory usage: 1.4 MB